import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { ethers } from "ethers";
import Web3Modal from "web3modal";
import Election from "../artifacts/contracts/Election.sol/Election.json";
import { electionAddress } from "../config";
import { useEffect } from "react";
import axios from "axios";

let rpcEndpoint = null;

if (process.env.NEXT_PUBLIC_WORKSPACE_URL) {
  rpcEndpoint = process.env.NEXT_PUBLIC_WORKSPACE_URL;
}

export default function Home() {
  const provider = new ethers.providers.JsonRpcProvider(rpcEndpoint);
  const electionContract = new ethers.Contract(
    electionAddress,
    Election.abi,
    provider
  );

  useEffect(() => {
    loadCandidates();
  }, []);

  async function loadCandidates() {
    try {
      // const tokenUri = await electionContract.tokenURI(i.tokenId);
      // const meta = await axios.get(tokenUri);
      // const data = await electionContract.getCandidates();
      // const items = await Promise.all(
      //   data.map(async ({ id, name, voteCount }) => {
      //     let item = {
      //       id,
      //       name,
      //       voteCount,
      //     };
      //     return item;
      //   })
      // );
      const count = await electionContract.candidatesCount();
      const ss = ethers.utils.FormatTypes(count._hex);
      console.log("electionContract :", ss);
      // console.log("tokenUri :", tokenUri);
      // console.log("meta :", meta);
    } catch (e) {
      console.log(e);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
